#!/bin/sh

source /etc/tizen-platform.conf

users_gid=$(getent group $TZ_SYS_USER_GROUP | cut -f3 -d':')

INHOUSE_ID="$users_gid"

init_vconf()
{
	vconftool set -t int memory/idle-screen/top 0 -i -g $users_gid -f
	vconftool set -t string file/private/org.tizen.menu-screen/engine "gl" -i -g $users_gid -f
	vconftool set -t string db/setting/menuscreen/package_name "org.tizen.menu-screen" -i -g $users_gid -f
}



init_vconf

# End of a file
